import type { AIProvider, AnalyzeInput } from '../AIProvider';
import { aiReportSchema, type AIReport } from '../schema';

/** A tiny heuristic so the mock picks a plausible category. */
function guessCategory(text: string): string {
  if (/econnrefused|database|prisma|\bsql\b|postgres|sqlite|query/i.test(text)) return 'Database';
  if (/timeout|network|fetch|socket|eaddrinuse|listen|dns/i.test(text)) return 'Network';
  if (/\bbuild\b|compile|webpack|tsc|module not found|cannot find module/i.test(text))
    return 'Build';
  return 'Runtime';
}

/**
 * The mock provider returns a deterministic, plausible report WITHOUT calling
 * any AI. It lets the whole app run with zero setup (no API key, no Ollama),
 * which is perfect for a first run, for tests, and for CI.
 */
export class MockProvider implements AIProvider {
  readonly name = 'mock';

  analyze({ excerpt, severityHint }: AnalyzeInput): Promise<AIReport> {
    const lines = excerpt.split('\n').filter((line) => line.trim() !== '');
    const signal = lines.find((line) => /error|exception|fatal|fail/i.test(line)) ?? lines[0] ?? '';
    // Drop a leading "timestamp LEVEL " prefix to get a cleaner title.
    const title =
      signal.replace(/^\S+\s+(?:INFO|WARN|ERROR|DEBUG)\s+/i, '').slice(0, 100) || 'Unknown issue';
    const category = guessCategory(excerpt);
    const keyLines = lines.slice(0, 5);

    const report = aiReportSchema.parse({
      title,
      severity: severityHint,
      category,
      keyLines,
      causes: [
        'Generated by the mock provider — set AI_PROVIDER to openai or ollama for a real analysis.',
      ],
      debugSteps: [
        'Reproduce the issue locally and watch the logs around the key lines.',
        'Check recent changes to the component named in the stack trace.',
      ],
      bugReportMarkdown:
        `## ${title}\n\n` +
        `**Severity:** ${severityHint}\n` +
        `**Category:** ${category}\n\n` +
        '### Key log lines\n\n```\n' +
        keyLines.join('\n') +
        '\n```\n\n' +
        '_Report generated by the LogLens mock provider._',
    });

    return Promise.resolve(report);
  }
}
